# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=30)),
                ('alt_symbol', models.CharField(blank=True, max_length=30, null=True)),
                ('code', models.CharField(blank=True, max_length=256, null=True)),
                ('logo', models.CharField(blank=True, max_length=256, null=True)),
                ('pair', models.CharField(max_length=64, null=True)),
                ('active', models.BooleanField(default=False)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freecoinage.Algorithm')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=30)),
                ('alt_symbol', models.CharField(blank=True, max_length=30, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Daemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('host', models.CharField(blank=True, max_length=256, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('rpcport', models.IntegerField(blank=True, null=True)),
                ('rpcuser', models.CharField(blank=True, max_length=256)),
                ('rpcpassword', models.CharField(blank=True, max_length=256)),
                ('balance', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('active', models.BooleanField(default=False)),
                ('coinid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freecoinage.Coin')),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('apihostname', models.CharField(blank=True, max_length=256, null=True)),
                ('apimarketsapi', models.CharField(blank=True, max_length=256, null=True)),
                ('apimarketmapname', models.CharField(blank=True, max_length=256, null=True)),
                ('apimarketmapid', models.CharField(blank=True, max_length=256, null=True)),
                ('apicurrencyapi', models.CharField(blank=True, max_length=256, null=True)),
                ('apiresults', models.CharField(blank=True, max_length=30, null=True)),
                ('apimapname', models.CharField(blank=True, max_length=30, null=True)),
                ('apimapsymbol', models.CharField(blank=True, max_length=30, null=True)),
                ('apimapalgo', models.CharField(blank=True, max_length=30, null=True)),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('afflink', models.CharField(blank=True, max_length=256, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InfoService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('apihostname', models.CharField(blank=True, max_length=256, null=True)),
                ('apimarketsapi', models.CharField(blank=True, max_length=256, null=True)),
                ('apicurrencyapi', models.CharField(blank=True, max_length=256, null=True)),
                ('apiresults', models.CharField(blank=True, max_length=30, null=True)),
                ('apimapname', models.CharField(blank=True, max_length=30, null=True)),
                ('apimapsymbol', models.CharField(blank=True, max_length=30, null=True)),
                ('apimapalgo', models.CharField(blank=True, max_length=30, null=True)),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('afflink', models.CharField(blank=True, max_length=256, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('marketcode', models.CharField(blank=True, max_length=30, null=True)),
                ('marketcode2', models.CharField(blank=True, max_length=30, null=True)),
                ('exchangecoincode', models.CharField(blank=True, max_length=30, null=True)),
                ('exchangecoincode2', models.CharField(blank=True, max_length=30, null=True)),
                ('exchangecurrencycode', models.CharField(blank=True, max_length=30, null=True)),
                ('exchangecurrencycode2', models.CharField(blank=True, max_length=30, null=True)),
                ('volume_coin', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('volume_currency', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('price_low', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('price_high', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('active', models.BooleanField(default=False)),
                ('coinid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freecoinage.Coin')),
                ('currencyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freecoinage.Currency')),
                ('exchangeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freecoinage.Exchange')),
            ],
        ),
        migrations.CreateModel(
            name='MarketLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_coin', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('volume_currency', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('price_low', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('price_high', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('marketid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freecoinage.Market')),
            ],
        ),
        migrations.CreateModel(
            name='Miner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('host', models.CharField(max_length=30)),
                ('port', models.CharField(max_length=30)),
                ('apiurl', models.CharField(max_length=30)),
                ('apiuser', models.CharField(max_length=30)),
                ('apipass', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MiningPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('host', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('port', models.CharField(blank=True, max_length=30, null=True)),
                ('apiurl', models.CharField(blank=True, max_length=256, null=True)),
                ('apikey', models.CharField(blank=True, max_length=256, null=True)),
                ('pooltype', models.CharField(blank=True, max_length=256, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='miner',
            unique_together=set([('host', 'port')]),
        ),
        migrations.AlterUniqueTogether(
            name='market',
            unique_together=set([('coinid', 'currencyid', 'exchangeid')]),
        ),
    ]
